import { db } from "./db";
import {
  users,
  members,
  deposits,
  withdrawals,
  notifications,
  activityLogs,
  systemBanks,
  products,
} from "@shared/schema";

export async function seedDatabase() {
  try {
    console.log("Checking database for existing data...");
    const existingUsers = await db.select().from(users).limit(1);
    if (existingUsers.length > 0) {
      console.log("Database already seeded, skipping...");
      return;
    }
  } catch (error) {
    console.log("Database tables may not exist, will seed now...", error);
  }

  console.log("Seeding database...");

  await db.insert(users).values([
    {
      id: "user-master-1",
      username: "master@master.com",
      password: "Asdf@@12",
      name: "Super Admin",
      email: "master@system.com",
      phone: null,
      role: "master",
      parentId: null,
      createdBy: null,
      invitationCode: null,
      isActive: true,
    },
    {
      id: "user-admin-1",
      username: "admin@system.com",
      password: "admin123",
      name: "Administrator",
      email: "admin@system.com",
      phone: null,
      role: "admin",
      parentId: "user-master-1",
      createdBy: "user-master-1",
      invitationCode: null,
      isActive: true,
    },
    {
      id: "user-admin-2",
      username: "admin2@system.com",
      password: "admin123",
      name: "Admin Dua",
      email: "admin2@system.com",
      phone: null,
      role: "admin",
      parentId: "user-master-1",
      createdBy: "user-master-1",
      invitationCode: null,
      isActive: true,
    },
    {
      id: "user-agent-1",
      username: "agent@system.com",
      password: "agent123",
      name: "Agen Cahaya",
      email: "agent@system.com",
      phone: "+6281234567001",
      role: "agent",
      parentId: "user-admin-1",
      createdBy: "user-admin-1",
      invitationCode: "CAHAYA001",
      isActive: true,
    },
    {
      id: "user-agent-2",
      username: "agent2@system.com",
      password: "agent123",
      name: "Agen Bintang",
      email: "agent2@system.com",
      phone: "+6281234567002",
      role: "agent",
      parentId: "user-admin-1",
      createdBy: "user-admin-1",
      invitationCode: "BINTANG02",
      isActive: true,
    },
  ]);

  await db.insert(members).values([
    {
      id: "m1",
      name: "Ahmad Rizki",
      email: "ahmad.rizki@email.com",
      password: "password123",
      phone: "+6281234567890",
      balance: 2500000,
      isLocked: false,
      lockReason: null,
      withdrawalLocked: false,
      withdrawalLockReason: null,
      status: "active",
      assignedAgentId: "user-agent-1",
      bankName: "BCA",
      bankAccountNumber: "1234567890",
      bankAccountName: "Ahmad Rizki",
      creditScore: 100,
    },
    {
      id: "m2",
      name: "Siti Nurhaliza",
      email: "siti.nur@email.com",
      password: "password123",
      phone: "+6281234567891",
      balance: 1750000,
      isLocked: false,
      lockReason: null,
      withdrawalLocked: false,
      withdrawalLockReason: null,
      status: "active",
      assignedAgentId: "user-agent-1",
      bankName: "Mandiri",
      bankAccountNumber: "5555666677",
      bankAccountName: "Siti Nurhaliza",
      creditScore: 85,
    },
    {
      id: "m3",
      name: "Budi Santoso",
      email: "budi.s@email.com",
      password: "password123",
      phone: "+6281234567892",
      balance: 500000,
      isLocked: true,
      lockReason: "Aktivitas mencurigakan terdeteksi",
      withdrawalLocked: true,
      withdrawalLockReason: "Verifikasi identitas diperlukan",
      status: "suspended",
      assignedAgentId: "user-agent-2",
      bankName: null,
      bankAccountNumber: null,
      bankAccountName: null,
      creditScore: 50,
    },
    {
      id: "m4",
      name: "Dewi Lestari",
      email: "dewi.l@email.com",
      password: "password123",
      phone: "+6281234567893",
      balance: 3200000,
      isLocked: false,
      lockReason: null,
      withdrawalLocked: false,
      withdrawalLockReason: null,
      status: "active",
      assignedAgentId: "user-agent-2",
      bankName: "BNI",
      bankAccountNumber: "9876543210",
      bankAccountName: "Dewi Lestari",
      creditScore: 120,
    },
    {
      id: "m5",
      name: "Eko Prasetyo",
      email: "eko.p@email.com",
      password: "password123",
      phone: "+6281234567894",
      balance: 800000,
      isLocked: false,
      lockReason: null,
      withdrawalLocked: true,
      withdrawalLockReason: "Batas penarikan harian tercapai",
      status: "active",
      assignedAgentId: "user-agent-1",
      bankName: null,
      bankAccountNumber: null,
      bankAccountName: null,
      creditScore: 75,
    },
    {
      id: "m6",
      name: "Calon Member Pending",
      email: "pending@email.com",
      password: "password123",
      phone: "+6281234567895",
      balance: 0,
      isLocked: false,
      lockReason: null,
      withdrawalLocked: false,
      withdrawalLockReason: null,
      status: "pending",
      assignedAgentId: "user-agent-1",
      bankName: null,
      bankAccountNumber: null,
      bankAccountName: null,
      creditScore: 100,
    },
  ]);

  await db.insert(deposits).values([
    {
      id: "d1",
      memberId: "m1",
      amount: 500000,
      status: "pending",
      rejectionReason: null,
      proofUrl: null,
      processedBy: null,
    },
    {
      id: "d2",
      memberId: "m2",
      amount: 1000000,
      status: "pending",
      rejectionReason: null,
      proofUrl: null,
      processedBy: null,
    },
    {
      id: "d3",
      memberId: "m4",
      amount: 250000,
      status: "approved",
      rejectionReason: null,
      proofUrl: null,
      processedBy: "user-admin-1",
    },
    {
      id: "d4",
      memberId: "m3",
      amount: 750000,
      status: "rejected",
      rejectionReason: "Bukti transfer tidak valid",
      proofUrl: null,
      processedBy: "user-admin-1",
    },
  ]);

  await db.insert(withdrawals).values([
    {
      id: "w1",
      memberId: "m1",
      amount: 300000,
      status: "pending",
      rejectionReason: null,
      bankName: "BCA",
      accountNumber: "1234567890",
      accountName: "Ahmad Rizki",
      processedBy: null,
    },
    {
      id: "w2",
      memberId: "m4",
      amount: 500000,
      status: "pending",
      rejectionReason: null,
      bankName: "BNI",
      accountNumber: "9876543210",
      accountName: "Dewi Lestari",
      processedBy: null,
    },
    {
      id: "w3",
      memberId: "m2",
      amount: 200000,
      status: "approved",
      rejectionReason: null,
      bankName: "Mandiri",
      accountNumber: "5555666677",
      accountName: "Siti Nurhaliza",
      processedBy: "user-admin-1",
    },
  ]);

  await db.insert(activityLogs).values([
    {
      id: "a1",
      action: "Deposit Disetujui",
      description:
        "Deposit sebesar Rp 250.000 untuk Dewi Lestari telah disetujui",
      memberId: "m4",
      userId: "user-admin-1",
      userRole: "admin",
      userName: "Administrator",
    },
    {
      id: "a2",
      action: "Akun Dikunci",
      description:
        "Akun Budi Santoso telah dikunci karena aktivitas mencurigakan",
      memberId: "m3",
      userId: "user-agent-1",
      userRole: "agent",
      userName: "Agent Team 1",
    },
    {
      id: "a3",
      action: "Penarikan Disetujui",
      description:
        "Penarikan sebesar Rp 200.000 untuk Siti Nurhaliza telah diproses",
      memberId: "m2",
      userId: "user-agent-2",
      userRole: "agent",
      userName: "Agent Team 2",
    },
    {
      id: "a4",
      action: "Top Up Saldo",
      description: "Saldo Ahmad Rizki ditambahkan Rp 1.000.000 oleh admin",
      memberId: "m1",
      userId: "user-admin-1",
      userRole: "admin",
      userName: "Administrator",
    },
  ]);

  await db.insert(notifications).values([
    {
      id: "n1",
      memberId: "m3",
      title: "Akun Anda Dikunci",
      message:
        "Akun Anda telah dikunci karena aktivitas mencurigakan terdeteksi. Silakan hubungi admin untuk informasi lebih lanjut.",
      type: "error",
      isRead: false,
    },
    {
      id: "n2",
      memberId: "m5",
      title: "Penarikan Dikunci",
      message:
        "Penarikan Anda telah dikunci karena batas penarikan harian tercapai. Silakan coba lagi besok.",
      type: "warning",
      isRead: false,
    },
  ]);

  await db.insert(systemBanks).values([
    {
      id: "sb1",
      bankName: "BCA",
      accountNumber: "1234567890",
      accountName: "PT Koperasi Sejahtera",
      isActive: true,
      createdBy: "user-master-1",
    },
    {
      id: "sb2",
      bankName: "BNI",
      accountNumber: "0987654321",
      accountName: "PT Koperasi Sejahtera",
      isActive: true,
      createdBy: "user-master-1",
    },
    {
      id: "sb3",
      bankName: "Mandiri",
      accountNumber: "1122334455",
      accountName: "PT Koperasi Sejahtera",
      isActive: true,
      createdBy: "user-admin-1",
    },
  ]);

  await db.insert(products).values([
    {
      id: "p1",
      name: "iPhone 15 Pro Max",
      price: 21999000,
      category: "Elektronik",
      imageUrl: null,
      rating: 48,
      reviews: 120,
      isActive: true,
      createdBy: "user-master-1",
    },
    {
      id: "p2",
      name: "Samsung Galaxy S24",
      price: 18999000,
      category: "Elektronik",
      imageUrl: null,
      rating: 48,
      reviews: 120,
      isActive: true,
      createdBy: "user-master-1",
    },
    {
      id: "p3",
      name: "MacBook Pro M3",
      price: 35999000,
      category: "Elektronik",
      imageUrl: null,
      rating: 49,
      reviews: 85,
      isActive: true,
      createdBy: "user-master-1",
    },
    {
      id: "p4",
      name: "AirPods Pro 2",
      price: 3999000,
      category: "Elektronik",
      imageUrl: null,
      rating: 47,
      reviews: 200,
      isActive: true,
      createdBy: "user-admin-1",
    },
    {
      id: "p5",
      name: "Nike Air Max",
      price: 2499000,
      category: "Fashion",
      imageUrl: null,
      rating: 46,
      reviews: 150,
      isActive: true,
      createdBy: "user-admin-1",
    },
    {
      id: "p6",
      name: "Vitamin C Serum",
      price: 299000,
      category: "Kesehatan",
      imageUrl: null,
      rating: 45,
      reviews: 300,
      isActive: true,
      createdBy: "user-agent-1",
    },
  ]);

  console.log("Database seeded successfully!");
}
